spring.datasource:
  url: jdbc:postgresql://localhost:5432/RADARCOVID?schema=configuration
  username: radarcovid
  password: radarcovid

contentful:
  url: https://preview.contentful.com/
  environment: master
